
#Wear down grass when passing on it.
["Desire Paths"]
	#Chance for blocks to transform each tick
	#Range: 0.0 ~ 1.0
	"Chance to transform" = 0.008
	#If true, speed will increase/decrease based off speed. The 'Chance to transform' will be based on walking.
	"Speed based chance" = true
	#Tall grass is broken when grass is transformed
	"Break Tall Grass" = true
	#Transform list of blocks
	"Transformation List" = ["minecraft:grass_block,minecraft:dirt", "minecraft:dirt,minecraft:coarse_dirt"]

