
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

	[types.leaves_type]

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

	[types.cut_block_type]

		[types.cut_block_type.philipsruins]
			obsidian_brick = true
			bone_bricks = true
			sculk_bone_bricks = true

		[types.cut_block_type.cinchsbetterdeepslate]
			mossy_cobbled_deepslate = true
			mossy_deepslate_brick = true
			mossy_deepslate_tile = true
			deepslate = true

		[types.cut_block_type.environmental]
			dirt_brick = true
			dirt_tile = true
			smooth_mud = true
			grass_thatch = true
			cattail_thatch = true
			duckweed_thatch = true
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.cut_block_type.clayworks]
			terracotta = true
			white_terracotta = true
			orange_terracotta = true
			magenta_terracotta = true
			light_blue_terracotta = true
			yellow_terracotta = true
			lime_terracotta = true
			pink_terracotta = true
			gray_terracotta = true
			light_gray_terracotta = true
			cyan_terracotta = true
			purple_terracotta = true
			blue_terracotta = true
			brown_terracotta = true
			green_terracotta = true
			red_terracotta = true
			black_terracotta = true
			terracotta_brick = true
			white_terracotta_brick = true
			orange_terracotta_brick = true
			magenta_terracotta_brick = true
			light_blue_terracotta_brick = true
			yellow_terracotta_brick = true
			lime_terracotta_brick = true
			pink_terracotta_brick = true
			gray_terracotta_brick = true
			light_gray_terracotta_brick = true
			cyan_terracotta_brick = true
			purple_terracotta_brick = true
			blue_terracotta_brick = true
			brown_terracotta_brick = true
			green_terracotta_brick = true
			red_terracotta_brick = true
			black_terracotta_brick = true

		[types.cut_block_type.buzzier_bees]
			honeycomb_brick = true
			honeycomb_tile = true

		[types.cut_block_type.upgrade_aquatic]
			beachgrass_thatch = true
			luminous_prismarine = true
			tooth_brick = true
			scute_shingle = true
			scute_pavement = true
			coralstone = true
			bubble_coralstone = true
			horn_coralstone = true
			tube_coralstone = true
			brain_coralstone = true
			fire_coralstone = true
			acan_coralstone = true
			finger_coralstone = true
			star_coralstone = true
			moss_coralstone = true
			petal_coralstone = true
			branch_coralstone = true
			rock_coralstone = true
			pillow_coralstone = true
			silk_coralstone = true
			chrome_coralstone = true
			prismarine_coralstone = true
			elder_prismarine_coralstone = true
			dead_coralstone = true
			kelpy_cobblestone = true
			kelpy_stone_brick = true
			kelpy_cobblestone_brick = true
			kelpy_cobblestone_tile = true
			driftwood = true
			river = true

		[types.cut_block_type.atmospheric]
			rosewood = true
			morado = true
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true
			polished_dolerite = true
			arid_sandstone = true
			smooth_arid_sandstone = true
			cut_arid_sandstone = true
			red_arid_sandstone = true
			smooth_red_arid_sandstone = true
			cut_red_arid_sandstone = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true
			carmine_shingle = true
			carmine_pavement = true

		[types.cut_block_type.autumnity]
			snail_shell_brick = true
			snail_shell_tile = true
			maple = true

		[types.cut_block_type.quark]
			ancient_planks = true
			azalea_planks = true
			blossom_planks = true
			duskbound_block = true
			iron_plate = true
			rusty_iron_plate = true
			midori_block = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			permafrost = true
			permafrost_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			thatch = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true

		[types.cut_block_type.supplementaries]
			fine_wood = true
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_block_type.betterarcheology]
			rotten = true
			cracked_mud_brick = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.vct]
			crafting_table = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			chest = true
			stripped_post = true
			ladder = true
			trapped_chest = true
			bookshelf = true
			hollow_log = true
			vertical_slab = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

