[Base]
	#Vanilla Explosions use a random number that changes the explosion power. With this enabled the ray strength will be as the explosion size.
	"Disable explosion randomness" = true
	#While enabled knockback is greatly increased by explosion size
	"Knockback scales with size" = true
	#Explosions will generate from the middle of the entity instead of bottom of their bounding box.
	"Explosion at half entity" = true
	#EXPERIMENTAL! This will make explosion blast blocks away. Blocks that can't land will drop the block as a TNT would have destroyed it.
	"Enable flying blocks" = false
	#If true, creepers explosions will drop no blocks.
	"Creeper collateral" = false
	#Entities can have a knockback_multiplier nbt tag that will override this.
	# Default: 1.0
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	"Knockback multiplier" = 1.0
	#Entities can have a damage_multiplier nbt tag that will override this.
	# Default: 0.85
	# Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	"Damage multiplier" = 0.85
	#Disabled if set to 0.
	# Default: 12
	# Range: > -2147483648
	"Limit explosion size" = 12
	#Like pre-1.14
	"Don't stack drops" = false
	#If true, potion effects from the exploder will be applied to the damaged entities
	"Apply effect from exploder" = true
	#If true, the overhaul will not be applied for explosions generated by non-entities. E.g. Supplementaries gunpowder
	"Don't apply to non-entities" = true
