# Use Cloth Config mod for the descriptions.
---
modules:
  enchantment: true
fallDamageReduction: 0.4
fallDamageThreshold: 6
speedReductionHorizontal: 0.9
speedReductionVertical: 0.9
modifyPathFinding: true
playerOnly: false
alwaysNotViewBlocking: true
alwaysLeafWalking: false
sounds:
  volume: 0.4
  playerOnly: false
