["S p"]
	#In vanilla when you start blocking with a shield, there's a 0.25 seconds (5 ticks) window where you are still not blocking. By default the windup is removed.
	# Default: 0
	# Range: > 0
	"Shield windup" = 0
	#If true shields will block only a certain amount of damage. If false the vanilla behaviour is used.
	"Shield block fixed damage amount" = true
	#The minimum damage dealt to the player for the shield to take damage. Vanilla is 3. E.g. With this set to 3, the shield will not be damaged if damage received is lower than 3.
	# Default: 0.0
	# Range: 0.0 ~ 3.4028234663852886E38
	"Min shield hurt damage" = 0.0
	#Makes shields always disable for 1.6 seconds like Combat Test snapshots.
	"Combat test shield disabling" = true
	#If true, crouching will block with the shield and you can attack while blocking.
	"Block with crouch" = true
	#If true, shields can be lifted only for a certain amount of time and will go on cooldown.
	"Lifted and cooldown" = true
	#When shields go on cooldown, the time is given by how much time the shield has been blocking. This defines the minimum cooldown in percentage for the shield to go on cooldown (e.g. if you just block for a few ticks, the cooldown will be 30% of the shield's cooldown).
	# Default: 0.3
	# Range: 0.0 ~ 1.0
	"Min cooldown" = 0.3
	#If true, enables a data pack that overrides the vanilla shield recipe with the mod's iron one.
	"Override vanilla shield recipe" = true
